redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/peter_scarfo/dev/gathersync/dist-web"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build:web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "https://gathersync-api-deploy.fly.dev/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]